language: python

python:
  - "2.7"

after_success:
  - codecov

branches:
  only:
    - master

env:
  - TOXENV=pylint
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=py27

before_install:
  pip install -r requirements-dev.txt

script:
  - tox
