language: python

python:
  - 3.6

after_success:
  - codecov

branches:
  only:
    - master

env:
  - TOXENV=pylint
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=bandit
  - TOXENV=rstlint
  - TOXENV=pydiatra
  - TOXENV=py36

script:
  - tox
